name: Retrain Model

on:
  schedule:
    - cron: "0 0 1 * *"  # Monthly at midnight on 1st
  push:
    paths:
      - 'data/creditcard_sample.csv'

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Train model
      run: python scripts/train_model.py
    
    - name: Deploy new model
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add models/
        git commit -m "Update model"
        git push
